In [139]:
import pandas as pd

In [140]:
data = {'Name':['Alice','Bob'],'Age':[25,30]}

In [126]:
data

{'Name': ['Alice', 'Bob'], 'Age': [25, 30]}

In [129]:
df=pd.DataFrame(data)

In [13]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [15]:
lst = [['Alice',25],['Bob',30]]

In [141]:
df=pd.DataFrame(lst,columns=['Name','Age'])

In [17]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [19]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [23]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [25]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [29]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [31]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [33]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [35]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [87]:
df['Gender']=['F','M']

In [38]:
df

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [41]:
df.drop('Age',axis=1,inplace=True)

In [42]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [44]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [46]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [48]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [88]:
df.groupby('Gender')['Age'].mean()
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [113]:
df1=pd.DataFrame({'key':[1,2],'name':['alice','bob']})
df2=pd.DataFrame({'key':[1,2],'age':[25,30]})

In [97]:
df1
df2

   key  age
0    1   25
1    2   30

In [98]:
pd.merge(df1,df2,on='key')

   key   name  age
0    1  alice   25
1    2    bob   30

In [58]:
df

    Name Gender
0  Alice      F
1    Bob      M

In [114]:
df1=df1.set_index('key')
df2=df2.set_index('key')

In [111]:
df1.join(df2)

      name  age
key
1    alice   25
2      bob   30

In [115]:
df1.join(df2)

      name  age
key
1    alice   25
2      bob   30

In [133]:
df

    Name  Age
0  Alice   25
1    Bob   30

In [119]:
df

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [ ]:
df.to_csv('output.csv',index=False)

In [142]:
df.sort_values('age')

KeyError: 'age'

In [ ]:
df['Age'].apply(lambda x: x + 1)

In [ ]:
df['Name'].unique()

In [ ]:
df['Age'].value_counts()